version: 2.1

# Add additional CircleCI Orbs dependencies
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/kubernetes
  kubernetes: circleci/kubernetes@0.3.0
  # https://circleci.com/orbs/registry/orb/circleci/helm
  helm: circleci/helm@0.1.2

jobs:
  # Run Helm Lint checks
  helm-lint:
    working_directory: ~/stackstorm-ha
    docker:
      - image: lachlanevenson/k8s-helm
    steps:
      - checkout
      - run:
          name: Prepare Helm
          command: |
            set -x
            helm init --client-only
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
            helm dependency update
      - run:
          name: Helm Lint Check (Community)
          command: helm lint
      - run:
          name: Helm template
          command: |
            mkdir -p community
            helm template --output-dir community .

      - persist_to_workspace:
          root: ~/stackstorm-ha/
          paths:
            - community
            # TODO: Fill an issue in https://github.com/garethr/kubeval
            # 'charts' contains 3rd party templates which doesn't validate against schema due to minor 'object != null' API validation issues

  # Run Kubernetes lint checks
  k8s-lint:
    docker:
      - image: garethr/kubeval
    steps:
      - attach_workspace:
          at: .
      - run:
          name: K8s Kubeval Lint Check (Community)
          command: kubeval $(find . -type f)
          working_directory: community/stackstorm-ha/templates/

  # Spin up minikube K8s cluster and run Helm chart & e2e tests on it
  helm-e2e:
    machine:
      # Available images https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - kubernetes/install
      - run:
          name: Install Minikube
          command: |
            sudo curl -fLo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo chmod +x /usr/local/bin/minikube
            minikube version
      - run:
          name: Create new K8s cluster
          command: sudo -E minikube start --vm-driver=none --cpus $(nproc) --memory 4096
          environment:
            CHANGE_MINIKUBE_NONE_USER: true
      - helm/install-helm-on-cluster
      - run:
          name: Update stackstorm-ha chart dependencies
          command: |
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
            helm dependency update
      - run:
          name: Helm install stackstorm-ha chart (Community)
          command: helm install --debug --wait --name stackstorm-ha .
      - run:
          name: Helm test (Community)
          command: helm test stackstorm-ha --parallel --cleanup
      - run:
          when: always
          name: Show created K8s resources (Community)
          command: kubectl get all

workflows:
  version: 2
  helm:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint
      - helm-e2e:
          requires:
            - helm-lint
            - k8s-lint
  # Run periodic nightly Helm tests to ensure there are no regressions
  helm-nightly:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint
      - helm-e2e:
          requires:
            - helm-lint
            - k8s-lint
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
